#!/bin/sh

flutter analyze .
if [ $? -ne 0 ]; then
  exit 1
fi

flutter format --set-exit-if-changed .
if [ $? -ne 0 ]; then
  exit 1
fi

flutter test
if [ $? -ne 0 ]; then
  exit 1
fi

dart fix --dry-run | grep 'Nothing to fix!'
if [ $? -ne 0 ]; then
  exit 1
fi